services:
  - type: web
    name: codocollab
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
    healthCheckPath: /
